name: Print Message from Repo A or B
on:
  repository_dispatch:
    types: [hello-event, hey-event]

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: |
          echo "Received: ${{ github.event.client_payload.message }}"
