
name: Updated Workflow
on:
  push:
    branches:
      - main
#Test
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add your workflow steps here
