
name: Updated Workflow
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add your workflow steps here

      #Test3

          - name: Updated Step
            run: echo 'Updated step'
          # Add more updated steps here
        